---
title: "Week 3: Data Frames/Loading Data/ggplot2"
linktitle: "Week 3: Data Frames/Loading Data/ggplot2"
date: "2020-01-20"
read_date: "2020-01-27"
menu:
  reading:
    parent: Readings
    weight: 2
type: docs
---

## Required

- [Combining functions usin g the pipe operator, %>%](https://ubc-dsci.github.io/introduction-to-datascience/wrangling.html#combining-functions-using-the-pipe-operator) - if you're confused about `%>%`, please read this.

## Optional

### Customizing ggplot2 

If you are interested in learning more about ggplot:

- Documentation for all `ggplot` features is available [here](https://ggplot2.tidyverse.org).
- RStudio also publishes a [ggplot cheat sheet](https://github.com/rstudio/cheatsheets/raw/master/data-visualization-2.1.pdf) that is really handy!
- [Customizing ggplot2 Cheatsheet](http://zevross.com/blog/2014/08/04/beautiful-plotting-in-r-a-ggplot2-cheatsheet-3/) is also handy, because it organizes ggplot2 commands by task.

### Using `tidyselect` (Intermediate Level)

Remember, `select()` works on columns.

`tidyselect` lets you select columns by matching names. In conjunction with the `across()` command, you can apply the same operation to multiple columns at once. This is especially handy when you need to produce a summary on all numeric columns.

You can run the `tidyselect` tutorial by running the code in your terminal:

```
library(tidyowl)
learn_tidyselect()
```