---
title: "Part 4. dplyr: mutate, group_by, summarize, across"
linktitle: "Part 4. dplyr: mutate, group_by, summarize, across"
date: "2021-01-26"
class_date: "2021-01-26"
output:
  blogdown::html_page:
    toc: true
menu:
  class:
    parent: Class sessions
    weight: 4
type: docs
weight: 4
# pdf: 
# thumb: 
editor_options: 
  chunk_output_type: console
---

## R Project files

Please download the part4 subfolder in [this folder link](https://www.dropbox.com/sh/q4z72523kl84ywp/AAASb1YIFRpxzrjOeq1FVcXua?dl=0) Be sure to unzip if necessary. "Knit" the part4.Rmd file to install packages and make sure everything is working with data loading.

## Class Video


<iframe width="560" height="315" src="https://www.youtube.com/embed/GGBlm21dyBE" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


View last year's class and materials [here](https://sph-r-programming.netlify.app/class/04-class/).

<!-- <iframe width="560" height="315" src="https://www.youtube.com/embed/yCPcijCj15c" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> -->

## Slides

No slides this week.

<!-- Open the class introduction slides in a separate window: <a href="https://sph-r-programming-2022.netlify.app/slides/01-introduction_slides#1" target="_blank">https://sph-r-programming-2022.netlify.app/01-introduction_slides#1</a> -->

<!-- ```{r echo=FALSE} -->
<!-- knitr::include_url('https://sph-r-programming-2022.netlify.com/slides/01-introduction_slides#1') -->
<!-- ``` -->

### Post-Class

Please fill out the following survey and we will discuss the results during the next lecture. All responses will be anonymous. The first two questions will count toward your attendance part of the grade.

- Clearest Point: What was the most clear part of the lecture?
- Muddiest Point: What was the most unclear part of the lecture to you?
- Anything Else: Is there something you'd like me to know?

<https://forms.gle/4tVx1mL7SzQx7MCu5>


## Muddiest Points/Clearest Points 

I will add the muddiest/clearest points from the survey after the first class.

