---
title: "Part 7. purrr"
linktitle: "Part 7. purrr"
date: "2021-02-17"
class_date: "2021-02-17"
output:
  blogdown::html_page:
    toc: true
menu:
  class:
    parent: Class sessions
    weight: 7
type: docs
weight: 7
# pdf: 
# thumb: 
editor_options: 
  chunk_output_type: console
---

## Class Video

<iframe width="560" height="315" src="https://www.youtube.com/embed/HiLrucrzYJM" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Slides

Open the slides in a separate window: <a href="https://sph-r-programming.netlify.com/slides/07_purrr#1" target="_blank">https://sph-r-programming.netlify.com/slides/07_purrr#1</a>

```{r echo=FALSE}
knitr::include_url('https://sph-r-programming.netlify.com/slides/07_purrr#1')
```

## Midterm will be returned by Friday (2/19)


### Post-Class

Please fill out the following survey and we will discuss the results during the next lecture. All responses will be anonymous.

- Clearest Point: What was the most clear part of the lecture?
- Muddiest Point: What was the most unclear part of the lecture to you?
- Anything Else: Is there something you'd like me to know?

http://bit.ly/sph504_survey

## Muddiest Points

> Purrr was a lot to take in, but with practice it should be vary useful

> [...] it seemed a lot more complicated actually seeing these functions used to perform tasks like performing linear regressions on multiple items in a list. I think I need to practice this to understand better.

> Most of the class was pretty muddy this time

> I think I just need to get more comfortable with all the purr functions

> The notation for building functions still confuses me. When I look back at the class Rmd, it gets overwhelming pretty fast. Writing functions is still pretty new, though.

Please reach out. I want you to understand this.

> dot notation

Stay tuned during class.

## Dear Ted

> Everyone's midterm project sounds really cool. It also seems like everyone came up with really creative ways to visualize the data. We don't have time to present them in class, but would it be a possibility to have classmates publish their midterms on the website if they are comfortable so we can see them and learn from what others did?

Check it out here: https://sph-midterm-projects.netlify.app

> When I first looked at part 7, I thought, oh, I'm not going to understand any of this! But you did a great job of teaching it, and I felt really comfortable with everything at the end. I think you'll do a great job teaching . notation too!

Thank you!

> There was a function you showed us that allowed us to arrange plots in the RMD by saving them as objects and then ordering them within the function, but now I can't find it.

That would be the `{patchwork}` package here: https://sph-r-programming.netlify.app/functions/patchwork_kempton/