---
title: "Part 9. `tidymodels`/Unsupervised Learning/Logistic Regression"
linktitle: "Part 9. `tidymodels`/Unsupervised Learning/Logistic Regression"
date: "2021-03-03"
class_date: "2021-03-03"
output:
  blogdown::html_page:
    toc: true
menu:
  class:
    parent: Class sessions
    weight: 9
type: docs
weight: 9
# pdf: 
# thumb: 
editor_options: 
  chunk_output_type: console
---

## Class Video

<iframe width="560" height="315" src="https://www.youtube.com/embed/BbrUnjNE3Yk" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Slides


Open the slides in a separate window: <a href="https://sph-r-programming.netlify.com/slides/09_machine_learning#1" target="_blank">https://sph-r-programming.netlify.com/slides/09_machine_learning#1</a>

```{r echo=FALSE}
knitr::include_url('https://sph-r-programming.netlify.com/slides/09_machine_learning#1')
```

## PCA Video (from StatQuest)

<iframe width="560" height="315" src="https://www.youtube.com/embed/HMOI_lkzW08" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## KMeans Video (from StatQuest)

<iframe width="560" height="315" src="https://www.youtube.com/embed/4b5d3muPQmA" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### Post-Class

Please fill out the following survey and we will discuss the results during the next lecture. All responses will be anonymous.

- Clearest Point: What was the most clear part of the lecture?
- Muddiest Point: What was the most unclear part of the lecture to you?
- Anything Else: Is there something you'd like me to know?

http://bit.ly/sph504_survey

## Muddiest Points

> The concept of clustering is still a bit muddy for me.

> PCA the graph showing contributions from each variable section was muddy for me.

> Still struggling to understand what a principal component analysis is

> To be honest, I wasn't really at 100% for this lecture and I wasn't able to follow what was going on that well, but I plan to review this on my own.

> Clustering

> still feeling a little confused on PCA. Will be rewatching the videos on the site.

> Clustering

> Pca

> Still trying to wrap my head around PCA/clustering. The homework will help.

> A lot of this was muddy. This jumped pretty far ahead of what we've learned in our other classes. It's hard for me to understand the code when I don't know the math and whatnot behind it.

Points taken. Hope the videos helped.

> What we're doing for our final project/what our options are for models

We will talk about this in class.

